### ISSUE TITLE
🌟 [EPIC] Admin: User overview

### ISSUE THREAD

**Issue by Elweyn** [dreammall-earth/dreammall.earth#1010]
## 🌟 EPIC
As administrator of the DreamMall: 
- I want to see an overview of the users that are in the system.
  - As information of a user I want to see: 
    - The name (Firstname & Lastname)
    - ~The email~ emails are personal data and a global email listing a potential security issue.
    - ~The package he choose & payment status~ that's a different feature

![image](https://github.com/user-attachments/assets/62be711f-cf9a-427e-b2fc-274692b54406)

## 🤖 ToDo
- [x] #1372
- [ ] 🚀 [Feature] Backend: Query to get User as Admin

**Comment by ogerly** [comment]
Grober Ablaufplan zur Umsetzung des Admin Interface
1. Initial Setup
    • Task: Aufsetzen von Storybook und Integration von Vuetify
    • Details: Storybook installieren, Vuetify ins System von Storybook integrieren, und sicherstellen, dass alles für die Tests sauber aufgesetzt ist.
    • Issue: #150 Aufsetzen von Storybook und Integration von Vuetify
2. Authentifizierung und Anmeldung
    • Task: Verbindung mit Authentik herstellen
        ◦ Subtask: Konfiguration von Authentik für das Admin Interface
        ◦ Subtask: Registrierung des Admin-Flows bei Authentik
        ◦ Subtask: Sicherstellen, dass die Admin Startseite nach der Anmeldung erreichbar ist
    • Details: Authentifizierung über http://localhost:3002/signin und Weiterleitung zu http://localhost:3002/ (bzw. auf stage1: https://stage1.admin.dreammall.earth/)
    • Issue: #145 Verbindung mit Authentik und Admin-Flows
3. Erstellung der Seiten
    • Task: Erstellung der Startseite
        ◦ Subtask: Design der Startseite
        ◦ Subtask: Implementierung der Startseite
    • Details: Initiale Darstellung der wichtigsten Informationen und Verknüpfungen zu den administrativen Funktionen.
    • Issue: #151 Erstellung der Startseite
    • Task: Erstellung der Nutzerübersichtsseite
        ◦ Subtask: Design der Nutzerübersichtsseite
        ◦ Subtask: Implementierung der Nutzerübersichtsseite
    • Details: Übersicht aller Nutzer mit Filter- und Suchfunktionen sowie detaillierten Informationen zu jedem Nutzer.
    • Issue: #152 Erstellung der Nutzerübersichtsseite
4. Design-Abnahme
    • Task: Interne Abstimmung des Designs
        ◦ Subtask: Designentwurf in Storybook dokumentieren
        ◦ Subtask: Interne Design-Abnahme und Freigabe
    • Details: Entwürfe intern abstimmen und im Issues-Tracker dokumentieren.
    • Issue: #153 Design-Abnahme und Freigabe
5. Testing und Qualitätskontrolle
    • Task: Durchführung von Tests
        ◦ Subtask: Unit Tests für alle Komponenten
        ◦ Subtask: Integration Tests für die vollständigen Seiten
    • Details: Sicherstellen, dass alle Komponenten und Seiten fehlerfrei funktionieren und den Anforderungen entsprechen.
    • Issue: #154 Testing und Qualitätskontrolle
6. Deployment
    • Task: Deployment auf Stage und Produktion
        ◦ Subtask: Deployment auf Stage (https://stage1.admin.dreammall.earth/)
        ◦ Subtask: Finales Deployment auf Produktionsumgebung
    • Details: Sicherstellen, dass die Änderungen korrekt auf den entsprechenden Umgebungen bereitgestellt werden.
    • Issue: #155 Deployment auf Stage und Produktion
7. Dokumentation
    • Task: Dokumentation der Umsetzung und Funktionen
        ◦ Subtask: Technische Dokumentation der Implementierung
        ◦ Subtask: Benutzerhandbuch für Administratoren
    • Details: Ausführliche Dokumentation für die interne und externe Nutzung.
    • Issue: #156 Dokumentation der Umsetzung und Funktionen
Zusammenfassung der Issues
    • #150: Aufsetzen von Storybook und Integration von Vuetify
    • #145: Verbindung mit Authentik und Admin-Flows
    • #151: Erstellung der Startseite
    • #152: Erstellung der Nutzerübersichtsseite
    • #153: Design-Abnahme und Freigabe
    • #154: Testing und Qualitätskontrolle
    • #155: Deployment auf Stage und Produktion
    • #156: Dokumentation der Umsetzung und Funktionen
