### ISSUE TITLE
🚀 [Feature] Frontend: Star map

### ISSUE THREAD

**Issue by Elweyn** [dreammall-earth/dreammall.earth#1017]
## 🚀 Feature

Who: users
What: See other users as star on the map
Why: I want to be able to get an overview on all other users in the application 

As User I want to see the open Meeting Rooms on the star map.

## 💬 Questions
Verschiedene Skopuse?
Gibt es Sterne ohne Rooms, Projekte, Teams & Personen?
Kann ich die Karte scrollen, zoomen, ...?
Punkte/Sterne haben Tooltip-Popup was steht drin?

## 🤖 ToDo
- [ ] It is absolutely not clear to us what kind of problem the star map tries to solve. Please make a Design Thinking iteration on this feature. What is the input data for the star map?

An inspiration could be D3 indeed. There is e.g. a ["force directed graph"](https://observablehq.com/@d3/force-directed-graph/2?intent=fork). This graph has *edges* and *nodes*. What are edges and nodes in the Dreammall? People who are joining tables?

**Comment by ogerly** [comment]
>>> example in parallax https://github.com/ogerly/parallax-starry-sky

**Comment by ogerly** [comment]
## Sternenkarte – Weltencafé

**Einleitung und Gespräch zur Sternenkarte**

Die Vorstellung ist es, alles in einer Art Sternenkarte abzubilden. Jeder Benutzer hat nach der Anmeldung ein eigenes Sternbild. Ebenso erhält jeder Tisch, jedes Projekt, jede Gruppe und jedes Tag ein Sternbild.

Ein Sternbild für einen Benutzer soll Folgendes abbilden:
* Seine Daten
* Seine Tische
* Seine Gruppen
* Seine Vernetzung im Allgemeinen

Ein Sternbild für einen Tisch, ein Projekt, eine Gruppe oder ein Tag soll beispielsweise alle Benutzer abbilden, die sich in diesem Sternbild (Cluster) befinden.

**Die Atmosphäre**

Die Stimmung soll wie folgt beschrieben werden: Ich befinde mich in einem gemütlichen Café, über mir ist die Decke offen und man sieht die Sterne, das Universum. Das Café soll einen begrenzten und übersichtlichen Raum darstellen. Man soll das Gefühl haben, alles an seinem Platz zu haben und einen Überblick zu behalten. Die Weite wird spürbar durch die geöffnete Decke, durch die die Weite erkennbar wird. Aber in dem Café (Startseite) fühlt man sich zuhause.

Durch Zoomen kann man sich in den weiten Raum über der geöffneten Decke auf die Sternenkarte zoomen.

**Anforderungen**

1. Alles und jeder muss ein Sternbild bekommen, und zwar in Canvas. Dieses darf sich nie verändern, muss genügend Punkte haben und einen sternbildähnlichen Charakter haben. Dies kann automatisch passieren, muss aber fest und ständig für alle Punkte gespeichert werden und wieder in derselben Form abrufbar sein.
2. Das Café dient als Startseite und Ausgangspunkt nach der Anmeldung. Die Sternenkarte dient als Navigations-, Übersichts- und Ansichtstool.
3. Im Cockpit soll für jeden Benutzer ein Sternensymbol erstellt werden. Noch besser wäre es, wenn der Benutzer es selbst erstellen oder per Klick generieren lassen könnte. Dies sollte einmalig möglich sein. Alternativ könnten wir mathematische Werte seines Anmeldedatums für die automatische Generierung nutzen.
4. Tags, die von Benutzern gesetzt werden und irgendwo gespeichert werden, erhalten ebenfalls ein Sternzeichen.
5. Gleiches gilt für Tische und Gruppen.

Für alles, was wir in der Karte darstellen wollen, gilt das Gleiche.

Dadurch können wir die Gewichtung (und damit die Größe der Bilder) anhand der Mitglieder berechnen oder durch deren Aktivitäten.

**Zusätzliche Gefühle beim Weltencafé**

Wenn ich mich in den Weltraum zoome, soll ich ein Gefühl von Erhabenheit, Aufsteigen, einen Überblick zu haben und wertfrei zu sein empfinden.

Ein wichtiges Ziel ist es, eine gewisse Übersichtlichkeit darzustellen. Durch unterschiedliche Größen der Cluster entsteht eine Gewichtung im Gesamtbild.

Gefühl: Wenn ich zu weit weg bin, also alle Sterne und Sternbilder sehe und sehr weit weg im Raum bin, habe ich das gegenteilige Gefühl zum Café: eine unendliche Weite, Unübersichtlichkeit und für einige vielleicht Überforderung. Auf der anderen Seite kann dieser Blickwinkel auch das Gefühl vermitteln, viele zu sein. Ein stärkendes und hoffnungsvolles Gefühl. Zugezoomt landen wir wieder in unserem gemütlichen und räumlich sehr begrenzten Café. Aber über uns ist die offene Weite. Dies kann ein Gefühl vermitteln von: „Hier bin ich zuhause, kenne alles, habe hier meine Leute und meinen Austausch.“

Es wäre möglich, in der Sternenkarte verschiedene Ansichten anzubieten, z.B. alle Vernetzungen zu einem Punkt oder von einem Punkt.

Die Technik, die sich für diese Sachen wohl am besten eignet, scheint nach momentanem Wissensstand Canvas zu sein. Das bedeutet zwar eine Lernkurve, aber es bringt das vielversprechendste Ergebnis.

**Was haben wir bisher?**

* Wir können Sternbilder zeichnen.
* Wir können sie im Raster ordnen und mathematisch verschieben. Die Gewichtung können wir berechnen und interaktiv setzen.
* Cluster und Sterne sind interaktiv.
* Wir haben einen anfänglichen Versuch mit Canvas, um aus einem Café in den Sternenhimmel zu zoomen (noch nicht zufriedenstellend).
