### ISSUE TITLE
🚀 [Feature] Authentik: Invitation link

### ISSUE THREAD

**Issue by Elweyn** [dreammall-earth/dreammall.earth#1179]
## 🚀 Feature
As User I want to be able to invite a new (~5 - 10) User with an Invitation Link.

**Comment by ulfgebhardt** [comment]
Closing in favor of
- https://github.com/dreammall-earth/dreammall.earth/issues/2350
- https://github.com/dreammall-earth/dreammall.earth/issues/2351
- https://github.com/dreammall-earth/dreammall.earth/issues/2352
