### ISSUE TITLE
🐛 [Bug]  error by tests "window is not defined"

### ISSUE THREAD

**Issue by ogerly** [dreammall-earth/dreammall.earth#1189]
## 🐛 Bug

Bei den Tests gibt es bei mir Errors wie unten beschrieben. 

es fehlt die globale window const. 

frontend/src/components/buttons/CreateButtonMobile.vue

error:

⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯ Uncaught Exception ⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯
ReferenceError: window is not defined
 ❯ Timeout.poll node_modules/vuetify/src/components/VImg/VImg.tsx:249:8
 ❯ listOnTimeout node:internal/timers:573:17
 ❯ processTimers node:internal/timers:514:7

This error originated in "src/components/buttons/CreateButtonMobile.test.ts" test file. It doesn't mean the error was thrown inside the file itself, but while it was running.
This error was caught after test environment was torn down. Make sure to cancel any running tasks before test finishes:
- cancel timeouts using clearTimeout and clearInterval
- wait for promises to resolve using the await keyword

**Comment by Elweyn** [comment]
@ogerly thanks for the issue. It seems to be a flaky test...

**Comment by ogerly** [comment]
js-dom einbinden 
https://vuetifyjs.com/en/getting-started/unit-testing/#setup-vitest
