### ISSUE TITLE
🚀 [Feature] Show Authentik user avatar

### ISSUE THREAD

**Issue by Bettelstab** [dreammall-earth/dreammall.earth#1256]
## 🚀 Feature
As a user, I want to have the same avatar across the whole DreamMall ecosystem.
Therefore, in the DreamMall, the default user avatar should be loaded from Authentik.

<img width="315" alt="Screenshot 2024-06-24 at 23 14 23" src="https://github.com/dreammall-earth/dreammall.earth/assets/3285528/7653e488-76c2-4961-a918-05cc9f38c05a">

<img width="223" alt="Screenshot 2024-06-24 at 23 14 48" src="https://github.com/dreammall-earth/dreammall.earth/assets/3285528/9b229547-87c7-4c6c-ba58-c674f18d547d">

---

Contents of #1733 :

## 🚀 Feature

Currently I am assigned a color for my Profile.
I want to have a picture as Profile or at least choose the color.
![image](https://github.com/user-attachments/assets/ab017cf6-5268-452e-b475-56b23251d932)

It is to be investigated how we can utilize authentik to serve those images.
Furthermore we might want to have a way for the user to set his profile picture within the application and not in authentik.

Having Authentik serve the image has following advantages
- image is available to other services
- we don't need to handle storage (most likely)

**Comment by Bettelstab** [comment]
Note: Change Applications => Providers => Scopes, and .env in frontend

**Comment by Bettelstab** [comment]
Possibly interesting:

Image Services:

https://github.com/thumbor/thumbor
https://github.com/h2non/imaginary

Blob Storage:
https://ceph.io/en/users/
https://min.io/
https://garagehq.deuxfleurs.fr/

Or blob in our database.

**Comment by roschaefer** [comment]
> Add 'avatar' to scopes in Authentik Admin Settings: Applications => Providers => Scopes, and .env in frontend

![image](https://github.com/user-attachments/assets/6bf34a88-88a2-4854-8aa2-3dad2531d665)

I don't see the `avatar` scope here. Where did you find this?

**Comment by roschaefer** [comment]
I had a look into the settings of Authentik:

![image](https://github.com/user-attachments/assets/c52acdbe-4b38-457d-8e68-71bf51e2fc14)

With the setting above, you can see this:

![image](https://github.com/user-attachments/assets/e8a33195-95d4-40de-b9a2-1b0809dd794c)

There is `AnyURL` option, so that we can configure any object storage and use `%(username)` in the URL to match the right resource.

>>  Any URL: If you want to use images hosted on another server, you can set any URL. Additionally, these placeholders can be used: 

There is another option below:

>> An attribute path like attributes.something.avatar, which can be used in combination with the file field to allow users to upload custom avatars for themselves.

But I think that's too cumbersome.


If you ask me, I think we can close this issue. Authentik does not serve images. We have to come up with our own solution and storage provider.

I also opened an issue here: https://github.com/goauthentik/authentik/issues/11425

**Comment by ulfgebhardt** [comment]
Authentik can handle this: https://github.com/goauthentik/authentik/discussions/6824

Following questions remain:
- Do we want authentik to handle this or is it better to implement a service doing this filling in a custom attributes field in authentik
- Can we receive the avatar url via oauth scope

**Comment by ulfgebhardt** [comment]
Close in favor of
- https://github.com/dreammall-earth/dreammall.earth/issues/2542
- https://github.com/dreammall-earth/dreammall.earth/issues/2540
- https://github.com/dreammall-earth/dreammall.earth/issues/2543
- https://github.com/dreammall-earth/dreammall.earth/issues/2544
- https://github.com/dreammall-earth/dreammall.earth/issues/2545

- https://github.com/dreammall-earth/dreammall.earth/issues/2546
- https://github.com/dreammall-earth/dreammall.earth/issues/2547
- https://github.com/dreammall-earth/dreammall.earth/issues/2548
