### ISSUE TITLE
💥 [DevOps] Deployment Process

### ISSUE THREAD

**Issue by Elweyn** [dreammall-earth/dreammall.earth#1259]
## 💥 DevOps

As DevOp I want to be able to deploy from GitHub on the different servers (stage, live, ...) a running system:
- Presenter: localhost:3001 => localhost:80 => reverse-proxy (...dreammall.earth)
- Frontend: localhost:3000 => localhost:80/app/ => reverse-proxy (...app.${server_domain})
- Admin: localhost:3002 => localhost:80/admin/ => reverse-proxy (...admin.${server_domain})
- Backend: localhost:4000 => localhost:80/api/ => reverse-proxy (...app.${server_domain}/api)
- Authentik: localhost:9000 => localhost:9000 => reverse-procy (...auth.${server_domain})

**Comment by roschaefer** [comment]
I think this can be closed after #1653
