### ISSUE TITLE
🐛 [Bug] When I try to join a table with the invitation link (join-room), I see BBB with an error message.

### ISSUE THREAD

**Issue by Bettelstab** [dreammall-earth/dreammall.earth#1380]
- I open the invitation link of a table which is supposed to exist
- I enter a name
- I expect to enter the table. But instead I get redirected to: https://cafe.dreammall.earth/?errors=[%7B%22message%22:%22You%20must%20provide%20your%20name%22,%22key%22:%22missingParamFullName%22%7D]

## 🐛 Bug
[
<img width="373" alt="Screenshot 2024-07-09 at 18 34 51" src="https://github.com/dreammall-earth/dreammall.earth/assets/3285528/f6e5482b-5a3c-494d-980c-3dec00db3eb4">
<img width="1111" alt="Screenshot 2024-07-09 at 18 34 57" src="https://github.com/dreammall-earth/dreammall.earth/assets/3285528/cf3e5eae-fc52-4b81-ae4d-276b4da8fe36">
](url)

**Comment by Elweyn** [comment]
Just Test if this error is still here.
