### ISSUE TITLE
🚀 [Feature] Backend: update user info mutation

### ISSUE THREAD

**Issue by Mogge** [dreammall-earth/dreammall.earth#1582]
## 🚀 Feature

A user wants to update the own profile with the following data:
- Their current availability to work (once set, can be changed but not removed)
- A one-line introduction text
- A list of details: location, work, languages, education, feeling (possibly multiple of the same)
- Diverse social media accounts

Here is the expected input as typescript type:
```
type DetailCategory = 'place' | 'work' | 'language' | 'education' | 'feeling'

type Detail = {
  category: DetailCategory
  text: string // max length 60 chars
}

type Profile = {
    name: string
    introduction?: string // max length 25 chars
    availability?: 'available' | 'partly_available' | 'busy'
    details: Detail[]
    social: { // For all social media accounts / links 60 chars max length
      discord?: string
      telegram?: string
      facebook?: string
      tiktok?: string
      snapchat?: string
      reddit?: string
      wechat?: string
      instagram?: string
      pintarest?: string
      linkedin?: string
      youtube?: string
      whatsapp?: string
      xing?: string
      x?: string
    }
}
```
 * Create a mutation to update the user table
 * Provide a mutation to update the user profile
 * Ensure that the `users` and `currentUser` queries provide the new data

**Comment by Mogge** [comment]
@Bettelstab Can you please update this issue when the input is clarified

**Comment by Bettelstab** [comment]
@Mogge Please see updated issue.

**Comment by roschaefer** [comment]
@Mogge how about nesting the user profile in the `User` as such:

```grapql

User {
  profile: Profile
}

```
