### ISSUE TITLE
🐛 [Bug] Avoid losing moderator permissions on page refresh

### ISSUE THREAD

**Issue by roschaefer** [dreammall-earth/dreammall.earth#1585]
## 🐛 Bug

I was in a BBB meeting with @mahula and I had to do a hard-refresh and lost my moderator permissions. Both of us could not take the presenter anymore.

We could fix this on our side only by creating a new room and doing things over.

### Possible solutions

How about having a deep-linked, own room per user that always gives moderator permissions to the "owner" - so at least one person will always have moderator permissions.

Could be done along with: https://github.com/dreammall-earth/dreammall.earth/issues/1007

**Comment by Mogge** [comment]
This should be fixed by the deep link of the table page. Please confirm
