### ISSUE TITLE
💥 [DevOps] Backup/Restore Authentik

### ISSUE THREAD

**Issue by roschaefer** [dreammall-earth/dreammall.earth#1588]
## 💥 DevOps

If we want to use our previous user accounts for in a deployment like #1451 we need to be able to export these user accounts and groups and restore them to a different authentik instance.

This is the equivalent of a backup/restore of Authentik. Have we ever tested that? (A backup strategy that has not been tested, is not a backup strategy).

### Implementation details

There are two ways to accomplish this:
1. A dump of postgresql
2. Export all objects as blueprints with `ak export_blueprint`, See [docs](https://docs.goauthentik.io/developer-docs/blueprints/export)

In both ways, we produce a file that needs to be downloaded. We need SSH access to download this file. Someone who has got SSH access already needs to publish the public SSH keys of the team to <https://auth.dreammall.earth>.

**Comment by ulfgebhardt** [comment]
@roschaefer is this still a thing?

**Comment by roschaefer** [comment]
> @roschaefer is this still a thing?

We talked in our pair-programming about this. It's still a thing for the currently used authentik instance. Maybe you can arrange SSH access for authentik on Friday.

**Comment by roschaefer** [comment]
We discussed this internally. I was able to download and restore user accounts to a local authentik instance. I've sent a `README.md` in our discord (because we don't want to publish it). This can be closed.
