### ISSUE TITLE
🐛 [Bug] Fix guest link in BBB meeting

### ISSUE THREAD

**Issue by Bettelstab** [dreammall-earth/dreammall.earth#1688]
## 🐛 Bug
<img width="358" alt="Screenshot 2024-08-09 at 11 11 25" src="https://github.com/user-attachments/assets/345c9e01-9eeb-4eef-ab23-cd80ddf6b8b8">

The guest link does not work anymore since rooms were renamed to tables.

We need it to contain `join-table` instead of `join-room`.

**Comment by Elweyn** [comment]
@ulfgebhardt this should be done in the backend/.env with the FRONTEND_INVITE_LINK_URL

**Comment by Elweyn** [comment]
After deployment I get:
![Image](https://github.com/user-attachments/assets/9230a230-4ccc-4943-9825-acd6fe475b0b)
