### ISSUE TITLE
🐛 [Bug] Ending a Session shows an Fullscreen Error

### ISSUE THREAD

**Issue by ulfgebhardt** [dreammall-earth/dreammall.earth#1731]
## 🐛 Bug

Ending a Session shows an Fullscreen Error in the iframe

![image](https://github.com/user-attachments/assets/28a86fa6-8d29-4a27-8d11-6c1cc86e070f)

To reproduce:
1. Create Table
2. End Session
3. See Error as shown above

**Comment by Bettelstab** [comment]
Solved by #1789
