### ISSUE TITLE
💬 [Question] [Design] No way to create a new table from table list

### ISSUE THREAD

**Issue by ulfgebhardt** [dreammall-earth/dreammall.earth#1734]
## 💬 Question

This is a question for the Designer.

As user I can see open tables, but I am unable to find a button to open a new Table in the corresponding list.

![image](https://github.com/user-attachments/assets/9e30c19d-6925-4aa7-875d-284e510cd330)

**Comment by Elweyn** [comment]
@ulfgebhardt I understood it like this:
We don't want to have multiple places where we create tables. 
So the icon is misleading since we should only find open tables here.

I wrote in our Konzeption channel a request to Hardi to create a Icon without +
