### ISSUE TITLE
🐛 [Bug] Navigating to cockpit and using back, does not correct the main menu

### ISSUE THREAD

**Issue by ulfgebhardt** [dreammall-earth/dreammall.earth#1735]
## 🐛 Bug

Navigating to cockpit and using back, does not correct the main menu. It still shows cockpit on top.

This error might be wise to ignore till we implement the cockpit - the error might go away.

Make sure to investigate if using the browser back-navigation works as expected before closing this issue.

![image](https://github.com/user-attachments/assets/9c42a0dd-c188-4adb-925a-90fb685fed90)

**Comment by Bettelstab** [comment]
Fixed by #1327 (there is no animation though)
