### ISSUE TITLE
🚀 [Feature] Restrict access to users without subscription or not enough credit after 7 days

### ISSUE THREAD

**Issue by roschaefer** [dreammall-earth/dreammall.earth#1742]
## 🚀 Feature
Who: admin
What: I want to prevent users to use the application who haven't paid their subscriptions or who have not enough credit based on their usage of the application. Users may have a 7 days period to use the application without subscription.
Why: There should be an incentive to support the application financially.

![image](https://github.com/user-attachments/assets/3d5e1d0f-26bc-4bb7-881a-a8548f741637)

**Comment by ulfgebhardt** [comment]
I dont think this is correct - the user must be able to login, so we can identify the paying user - correct me if i am wrong.

**Comment by roschaefer** [comment]
> I dont think this is correct - the user must be able to login, so we can identify the paying user - correct me if i am wrong.

What do you mean with "identify the paying user"? :thinking:

**Comment by ulfgebhardt** [comment]
Closing in favor of https://github.com/dreammall-earth/dreammall.earth/issues/2674 & https://github.com/dreammall-earth/dreammall.earth/issues/2673
