### ISSUE TITLE
💥 [DevOps] Request Browserstack Open Source Access

### ISSUE THREAD

**Issue by ulfgebhardt** [dreammall-earth/dreammall.earth#182]
## 💥 DevOps

Received project URL: https://github.com/dreammall-earth/dreammall.earth. One or more of the following validation checks failed:

1. Project should be at least 3 months old.
2. Project must contain valid open source licence.
3. Project's README.md file must contain the text 'This project is tested with Browserstack.' without quotes. You would have received an email regarding the same, please check it for further details.

When we tried in January it seemed like [1] was not yet fullfilled.

Retried at 12. April 2024 via https://www.browserstack.com/open-source
![browserstack_registration](https://github.com/dreammall-earth/dreammall.earth/assets/3883288/0883b57d-c023-48c6-abfd-69d9559c74c4)

**Comment by mahula** [comment]
I contacted BrowserStack support regarding our BrowserStack Open Source Project features.

**Comment by mahula** [comment]
Things are clear now.
We have sponsored Browserstack acces to their Open Source Program:

- exacctly one account
- exactly one user for Live testing
  - web applications on [browsers and mobile devices](https://www.browserstack.com/live)
  - apps on [mobile devices](https://www.browserstack.com/app-live)
- up to 5 parallel users for automated testing

More detailns regarding our account in our Discord.
