### ISSUE TITLE
💥 [DevOps] Reinvestigate the Figma-Storybook Connection

### ISSUE THREAD

**Issue by ulfgebhardt** [dreammall-earth/dreammall.earth#185]
## 💥 DevOps

Reinvestigate the Figma-Storybook Connection

@ogerly, @maeckes1, @Bettelstab want to investigate with Hardi if there is a better integration possible with Figma, Chromatic and Storybook.

From @ogerly 

### Vorteile der Integration von Chromatic
1. **Automatisierte visuelle Tests**: Chromatic vergleicht Screenshots von UI-Komponenten, um sicherzustellen, dass Änderungen am Code keine unbeabsichtigten visuellen Änderungen verursachen.
2. **Kollaboration**: Es ermöglicht Teammitgliedern, visuelle Änderungen zu überprüfen und zu kommentieren, was die Kommunikation und Effizienz verbessert.
3. **Dokumentation**: Automatisches Erstellen einer lebendigen Komponentenbibliothek, die als Single Source of Truth dient und hilft, Konsistenz über das gesamte Produkt hinweg zu bewahren.

#### Schritt 1: Design in Figma
- **Figma Setup**: Beginne mit einem vollständigen UI-Design in Figma. Nutze Komponenten und Design Tokens, um Konsistenz zu gewährleisten.

#### Schritt 2: Exportieren von Designs
- **Assets und Styles exportieren**: Exportiere CSS-Code, Farben, Schriftarten und Bilder aus Figma, die in deinem Vue-Projekt verwendet werden sollen.

#### Schritt 3: Entwicklung in Vue
- **Komponenten erstellen**: Erstelle Vue-Komponenten, die die exportierten Designs nutzen. Verwende Vuetify oder Tailwind CSS für die Stilgebung, je nach Projektanforderungen.
- **Storybook Integration**: Integriere diese Komponenten in Storybook, um sie isoliert zu entwickeln und zu testen.

#### Schritt 4: Integration von Chromatic
- **Chromatic Setup**: Richte Chromatic ein, um es mit deinem Storybook zu verbinden. Dies wird in der Regel durch Hinzufügen eines NPM-Pakets zu deinem Projekt und Konfigurieren einiger Einstellungen in deiner CI/CD-Pipeline erreicht.
- **Automatisierte Tests**: Führe visuelle Regressionstests mit Chromatic durch, um sicherzustellen, dass neue oder geänderte Komponenten visuell wie erwartet funktionieren.

**Comment by ogerly** [comment]
https://youtu.be/p-1n1c8B4Vo


hier was ich rausgefunden habe. 
im video:

- vuetify plugin im dev mode

- erstellen eines beispiels.

- ausführen im vs-code


offen ist noch: 

- custom-css ... (wobei ich denke das dies da im ganzen rausfällt. da muss ich aber tiefer forschen)

- github anbindung

https://youtu.be/p-1n1c8B4Vo 
YouTube
busFaktor() Verein
vue  vuetify  figma  vscode  :: example

so wie es im vs-code läuft .. so würde es auch im storybook aufrufbar sein. so das eine genaues nebeneinander stellen der figma arbeit und der storybook arbeit möglich ist.
das einigen auf die LIB und das synchronisieren von designer und entwickler ist gewährleistet.

was das für den designer an einschrenkung bedeutet kann ich schlecht aus meiner sicht sagen.

**Comment by ogerly** [comment]
**Vuetify for Figma:  Analyse**

### Übersicht
**Vuetify for Figma** ist ein Toolset, das speziell für die Integration von Vuetify-Komponenten in Figma entwickelt wurde. Es bietet Design- und Entwicklungsteams die Möglichkeit, Vuetify-Designs schnell und effizient in Figma zu erstellen und zu prototypisieren. 

### Hauptmerkmale
1. **Komplettes UI Kit**: Enthält alle Vuetify-Komponenten wie Buttons, Dialoge, Formularsteuerelemente usw.
2. **Stile und Themes**: Vorlagen für verschiedene Vuetify-Themes, um das Design an bestehende Projekte anzupassen.
3. **Responsive Layouts**: Komponenten sind so gestaltet, dass sie auf verschiedenen Bildschirmgrößen gut aussehen.
4. **Aktualisierte Bibliothek**: Regelmäßige Updates, um mit den neuesten Vuetify-Versionen Schritt zu halten.

### Vorteile
- **Zeitersparnis**: Beschleunigt den Designprozess durch vorgefertigte Komponenten.
- **Konsistenz**: Stellt sicher, dass Designs den Vuetify-Richtlinien entsprechen.
- **Einfachheit**: Leicht zu bedienen, selbst für Designer ohne tiefgehende Vuetify-Kenntnisse.

### Nachteile
- **Kosten**: Es ist nicht kostenlos und kann je nach Teamgröße und Projektbudget teuer sein.
- **Abhängigkeit**: Starke Abhängigkeit von Vuetify, was Einschränkungen bei der Anpassung bedeuten kann.

### Wann es brauchbar ist
- **Prototyping**: Ideal für schnelles Erstellen von Prototypen, die Vuetify-Komponenten verwenden.
- **Kollaboration**: Nützlich für Teams, die eng zwischen Design und Entwicklung zusammenarbeiten und Konsistenz benötigen.
- **Dokumentation**: Hilfreich, um Design-Spezifikationen für Entwickler bereitzustellen.

### Fazit
**Vuetify for Figma** ist ein wertvolles Tool für Teams, die Vuetify verwenden und eine nahtlose Integration zwischen Design und Entwicklung suchen. Es ist besonders nützlich, wenn Geschwindigkeit und Konsistenz im Designprozess entscheidend sind.

**Comment by ulfgebhardt** [comment]
Closing as there is still no real solution for an automation
