### ISSUE TITLE
🐛 [Bug] `.env.production` break local & stage environment

### ISSUE THREAD

**Issue by ulfgebhardt** [dreammall-earth/dreammall.earth#1851]
## 🐛 Bug

`.env.production` break local & stage environment.

There is a `.env.production` checked in which disturbs local & stage deployment.
Currently the solution is to delete the `.env.production` locally and remote to get things running.
The project should run out of the box without the need to delete stuff.

This is related to https://github.com/dreammall-earth/dreammall.earth/issues/1504

**Comment by roschaefer** [comment]
@ulfgebhardt I will close this as it is a duplicate of #1504
