### ISSUE TITLE
🔧 [Refactor] Authentik: Signup Flow - Account Confirmation Token Expiration

### ISSUE THREAD

**Issue by mahula** [dreammall-earth/dreammall.earth#1867]
## 🔧 Refactor
In the [DreamMall signup flow](https://github.com/dreammall-earth/dreammall.earth/blob/master/authentik/blueprints/dreammall/dreammallearth-enrollment.yaml) an email is send containing the account confirmation link.
The link's token has a default expiration time set to **30** minutes.
This seems quite short.

How long should the account confirmation token be valid?

**Comment by ulfgebhardt** [comment]
Is it possible to request a new confirmation?

**Comment by ulfgebhardt** [comment]
An invalid token sends you without error back to the signup page - it is possible to signup the same user again. I think this is sufficient for now.
