### ISSUE TITLE
🚀 [Feature] DM Button: Edit Table before opening it

### ISSUE THREAD

**Issue by ulfgebhardt** [dreammall-earth/dreammall.earth#1918]
## 🚀 Feature

DM Button: Edit Table before opening it

Clarify with @Hardy-Hart-am-Start before starting

There is a new Menu, which allows an unser to edit an existing not yet opened table before opening it:

![image](https://github.com/user-attachments/assets/37c9299a-8446-46ce-8f2c-6dd804606406)

Before:
![image](https://github.com/user-attachments/assets/7c95b79b-df60-4c97-9861-3c6b2425f894)

**Comment by Bettelstab** [comment]
Clarification from Hardi: After leaving my mall talk table, I cannot join it again (unless I've got the link). I just create a new table and the old one is deleted in the process. The default name can be taken from my last table, the invitee list should be clean.
