### ISSUE TITLE
🔧 [Refactor] DM Button: Style Edit Table

### ISSUE THREAD

**Issue by ulfgebhardt** [dreammall-earth/dreammall.earth#1919]
## 🔧 Refactor

DM Button: Style Edit Table:
Current Version:
![image](https://github.com/user-attachments/assets/2147aa8a-8de4-4a61-8df4-a99ecd53efe6)

Intended Version:
<img width="486" alt="Screenshot 2024-09-02 at 11 44 42" src="https://github.com/user-attachments/assets/4f8b2d7f-bb67-4cb8-b4b3-bb630944162e">

**Comment by sebastian2357** [comment]
- [ ] To finish this issue I need to learn how to manage styles by bright/dark themes.

Current state:

![image](https://github.com/user-attachments/assets/9cea282c-d98e-4329-88eb-1fd1362f7ebc)

**Comment by sebastian2357** [comment]
Hint: the icons are not identical to icons used in the drafts. I requested Hardi to give me an approval for this or to deny it.
