### ISSUE TITLE
🐛 [Bug] DM Button: Copy Link Menu

### ISSUE THREAD

**Issue by ulfgebhardt** [dreammall-earth/dreammall.earth#1920]
## 🐛 Bug

DM Button: Copy Link Menu

The Copy Link Menu is missing and there is no visual Feedback when copying a link

![image](https://github.com/user-attachments/assets/a462e20b-e430-4f1c-a427-7e5be530289e)

Figma:

![image](https://github.com/user-attachments/assets/b53ae45c-767d-41bc-a161-f53dc9fdcd0c)

**Comment by sebastian2357** [comment]
To be able to finish this issue I need a draft from Hardi about the visual feedback of the copy button.

**Comment by sebastian2357** [comment]
This tickets handled a lot more things than it was required in this tickets, but all other points were related to the ticket's subject. See the PR for a full list of completed todos.
