### ISSUE TITLE
🐛 [Bug] DM Button: Edit Table - is not reflected in current Meeting

### ISSUE THREAD

**Issue by ulfgebhardt** [dreammall-earth/dreammall.earth#1921]
## 🐛 Bug

DM Button: Edit Table - is not reflected in current Meeting

![image](https://github.com/user-attachments/assets/d110bbae-5073-47cb-99e0-c2bc9fdfb478)

Changing those settings is not reflected in the current Meeting. The next Meeting is affected tho.

Investigate
- if we can change settings for an existing Meeting in BBB
- if we can change the settings on DM Side to simulate the changed settings
- if we need to change the flow according to what BBB allows us to do

After updating a table the changes must be pushed to the clients via subscription

**Comment by Bettelstab** [comment]
It was agreed on that for now we hide the settings in an open meeting.
