### ISSUE TITLE
🐛 [Bug] DM Button: Making a Meeting private has no effect on visibility

### ISSUE THREAD

**Issue by ulfgebhardt** [dreammall-earth/dreammall.earth#1922]
## 🐛 Bug

DM Button: Making a Meeting private has no effect on visibility.

Even if we start the Meeting again, the privat flag is not saved nor does it affect the visibility of the Meeting for the users

![image](https://github.com/user-attachments/assets/05f8cfd0-a049-4814-ba85-e09fdfeb7f0e)

**Comment by Bettelstab** [comment]
Will be possibly solved by #1940 ?

**Comment by Elweyn** [comment]
Could not test it properly on the PR #2027 it is merged but in test and we can close it if it works properly
