### ISSUE TITLE
🐛 [Bug] DM Button: Edit name, visibility vs Settings

### ISSUE THREAD

**Issue by ulfgebhardt** [dreammall-earth/dreammall.earth#1926]
## 🐛 Bug

DM Button: Edit name, visibility vs Settings

Current implementation

![image](https://github.com/user-attachments/assets/7be60126-d282-425d-852a-31cec0aef05b)

Figma:

Creation Flow
![image](https://github.com/user-attachments/assets/181e1e05-b8aa-4d2b-affc-f493e349c190)

Edit flow
![image](https://github.com/user-attachments/assets/d098fb36-f004-4cac-8b41-13325f9fb291)

**Comment by sebastian2357** [comment]
- [ ] Panel color + transparency + filter
- [ ] Pen icon
- [ ] Button color
- [ ] Text Mall Talk
- [ ] "public" and "private" should be shown in dependency to switch button value
- [ ] usage of DM switch button

Hints:

- Hardi approved the merging of the dialogs "name" and "visibility"
- Hardi approved that only one switch button required

**Comment by sebastian2357** [comment]
The following open points have to be handled in further tickets:

- Pen icon => icon does not exist in icon library
- SwitchButton => is not ready for a more complex use
- Gradient + Round border => is not supported by css directly, needs a workaround
