### ISSUE TITLE
💬 [Question] How do we inform users invited to a Meeting?

### ISSUE THREAD

**Issue by ulfgebhardt** [dreammall-earth/dreammall.earth#1928]
## 💬 Question

How do we inform users invited to a Meeting?
![image](https://github.com/user-attachments/assets/129d0eb8-6374-436f-a46e-5505922f770d)

**Comment by ulfgebhardt** [comment]
Figma offers this Solution


![Image](https://github.com/user-attachments/assets/61e6e730-aba5-4e65-bd58-07887dc3a3e7)

TODO: Clarify with devs

**Comment by Elweyn** [comment]
@Hardy-Hart-am-Start and @ulfgebhardt 
I just want to remember the problems that @Mogge pointed out for this:
- If we add this we recreate some existing services (Discord, Zoom, ...)
- We need to know if a User is online
  - If he is not we need to do something like missed calls in case they come on and see a missed MallTalk that has been closed
- I did not see a possibility in the API to connect to a BBB Meeting with only microphone or directly with the camera. This is a configuration on the Meeting, I did not look in the BBB API to look if i am wrong with this point.

**Comment by ulfgebhardt** [comment]
Closing in favor of:
- https://github.com/dreammall-earth/dreammall.earth/issues/2228
- https://github.com/dreammall-earth/dreammall.earth/issues/2229
- https://github.com/dreammall-earth/dreammall.earth/issues/2231
