### ISSUE TITLE
🔧 [Refactor] Frontend: Design Join-As-Guest Page

### ISSUE THREAD

**Issue by ulfgebhardt** [dreammall-earth/dreammall.earth#1947]
## 🔧 Refactor

Frontend: Design Join-As-Guest Page

Current State:
![image](https://github.com/user-attachments/assets/ddc0c75c-dfa0-43df-a420-8d05bd791286)
The mobile view of the join Room as Guest ist gruesome:
![image](https://github.com/user-attachments/assets/93844b6a-a88d-433b-b801-a53a1cefab59)

New Designs in Figma unter "Tisch als Gast"

![image](https://github.com/user-attachments/assets/59487505-d17d-4125-9e9d-a05263dd0bf3)

Remarks on this:
- This is its own Page since it does not require a login
- The menu must be different, since we don't need the user to be able to navigate to his profile/logout or any of that
- The starmap in the background can be neglected for now - it is unclear if this will show the starmap with guest data or it will be a picture. Please use the starmap background color for page background , so we can estimate the style when the starmap will be present

**Comment by sebastian2357** [comment]
@Hardy-Hart-am-Start Can you please send me the background image?
