### ISSUE TITLE
🐛 [Bug] Guest Link cannot be stable

### ISSUE THREAD

**Issue by ulfgebhardt** [dreammall-earth/dreammall.earth#1948]
## 🐛 Bug

Guest Link cannot be stable between two Meetings, since a user can join any meeting on that table.
> https://stage1.app.dreammall.earth/join-table/1

The Guest link should be bound to the specific meeting in BBB. A suggestion is to use the internal meeting id.
>  'internal-meeting-id': 'b070c2de30140b9f77b7fa2318de762112e592c5-1725451926427'
> https://stage1.app.dreammall.earth/joinTable/b070c2de30140b9f77b7fa2318de762112e592c5-1725451926427

**Comment by Mogge** [comment]
As we must pass the link to the BBB on creation of the meeting, we cannot use any information given by BBB.
