### ISSUE TITLE
🐛 [Bug] Invalid meeting names

### ISSUE THREAD

**Issue by Bettelstab** [dreammall-earth/dreammall.earth#2004]
## 🐛 Bug
I can use "," to create a table. When I try to join the table, there is an error because the BBB meeting cannot be created.

**Comment by Hardy-Hart-am-Start** [comment]
https://www.figma.com/design/nkCyyDFx7fGeBnguwpardz/Dreammall-pr%C3%A4si?node-id=4613-86372&m=dev

In Figma ist eine Vorlage für diesen Fall abgebildet und bereit zur Bearbeitung.

**Comment by ulfgebhardt** [comment]
closing in favor of https://github.com/dreammall-earth/dreammall.earth/issues/2569
