### ISSUE TITLE
💬 [Research] Videokonferenz Werkzeug

### ISSUE THREAD

**Issue by ulfgebhardt** [dreammall-earth/dreammall.earth#21]
## 💬 Question

Bitte untersuche die Frage, welche Werkzeuge zur Videokonferenz es gibt. Alles was nicht self-hosted+open source ist kannst du unter einem Punkt abhandeln und muss nicht weiter untersucht werden (z.B. Skype).

Der Fokus sollte auf BigBlueButton liegen, das scheint weit verbreitet und daher eine gute Lösung.

Wichtige Fragen sind:
- Welche Fähigkeiten/Möglichkeiten bietet BBB?
- In wie weit können wir es Designen/Nur Teile verwenden?

Ergebnis sollte sein:
- Eine Präsentation der Ergebnisse max 15min
- Ein Dokument, welches Beschreibt, welche Teile von Hardi wie gestaltet werden können, damit er die Software entsprechend in sein Design einplanen kann. (gerne auch in der Präsentation kurz vorgestellt)
- Ein Dokument welche Fähigkeiten BBB hat, ggf ein Vergleich mit anderen Werkzeugen

**Comment by Elweyn** [comment]
There is a list of over 100 alternatives to BigBlueButton!

Self-Hosted & Open-Source:
- BBB: Java / ReactJS (Video stream, board, privat chat, public chat, ...)
  - Architecture: https://docs.bigbluebutton.org/development/architecture/: 
![External](https://github.com/dreammall-earth/dreammall.earth/assets/33051975/e2d6310a-b4f6-4e9a-9cd0-2d13acb439f8)
    - bbb-web -- Implements the BigBlueButton API and conversion of documents for presentation
    - akka-bbb-apps -- Server side application that handles the state of meetings on the server
    - bbb-html5 -- HTML5 client that loads in the browser. The client server-side Meteor application that leverages MongoDB and React.js
    - bbb-learning-dashboard -- a live dashboard available to moderators, which displays user activity information that can be useful for instructors
    - bbb-fsesl-akka -- Component to send commands to FreeSWITCH
    - bbb-playback-presentation -- Record and playback script to create presentation layout
    - bbb-export-annotations -- Handles capture of breakout content and annotated presentation download
    - bbb-webrtc-sfu -- Server that bridges incoming requests from client to Kurento
    - kurento-media-server -- WebRTC media server for sending/receiving/recording video (webcam and screen share)
    - bbb-freeswitch-core -- WebRTC media server for sending/receiving/recording audio
  - API: https://docs.bigbluebutton.org/development/api/:
  - Customization: example: https://github.com/smith010anthony/bigbluebutton-customized
- Jitsi: TypeScript (No board, no private messages)
  - https://github.com/jitsi/jitsi-meet 
  - IFrame (https://jitsi.github.io/handbook/docs/dev-guide/dev-guide-iframe)
- Briefing: TypeScript (no board, no private chat, ...)
  - https://github.com/holtwick/briefing

Non self-hosted / open-source:
- Freemium and/or Proprietary
  - Zoom
  - Microsoft Teams
  - Google Meet
  - Whereby
  - Cisco Webex Meetings
  - Skype Meet Now

**Comment by Elweyn** [comment]
BigBlueButton API URL: https://docs.bigbluebutton.org/development/api 

This API enables you to:
- create meetings:
  - Example Requests:
    - http://yourserver.com/bigbluebutton/api/create?name=Test&meetingID=test01&checksum=1234
    - http://yourserver.com/bigbluebutton/api/create?name=Test&meetingID=test01&moderatorPW=mp&attendeePW=ap&checksum=wxyz
    - http://yourserver.com/bigbluebutton/api/create?name=Test&meetingID=test01&moderatorPW=mp&attendeePW=ap&meta_presenter=joe&meta_category=education&checksum=abcd

  - Example Response:
    - Success:
    ```XML
    <response>
      <returncode>SUCCESS</returncode>
      <meetingID>Test</meetingID>
      <internalMeetingID>640ab2bae07bedc4c163f679a746f7ab7fb5d1fa-1531155809613</internalMeetingID>
      <parentMeetingID>bbb-none</parentMeetingID>
      <attendeePW>ap</attendeePW>
      <moderatorPW>mp</moderatorPW>
      <createTime>1531155809613</createTime>
      <voiceBridge>70757</voiceBridge>
      <dialNumber>613-555-1234</dialNumber>
      <createDate>Mon Jul 09 17:03:29 UTC 2018</createDate>
      <hasUserJoined>false</hasUserJoined>
      <duration>0</duration>
      <hasBeenForciblyEnded>false</hasBeenForciblyEnded>
      <messageKey>duplicateWarning</messageKey>
      <message>This conference was already in existence and may currently be in progress.</message>
    </response>
    ```
    - Failed:
    ```XML
    <response>
      <returncode>FAILED</returncode>
      <messageKey>checksumError</messageKey>
      <message>Checksums do not match</message>
    </response>
    ```
  - Pre-upload Slides
  You can upload slides within the create call. If you do this, the BigBlueButton server will immediately download and process the slides.
  You can pass the slides as a URL or embed the slides in base64 as part of the POST request. For embedding the slides, you have to send a HTTPS POST request (by default, the total size of the POST request can't exceed 2MB, so embedding very large slides won't work). The URL Resource has to be the same as the previously described.
  In the body part, you would append a simple XML like the example below:
  ```XML
  <modules>
    <module name="presentation">
      <document url="http://www.sample-pdf.com/sample.pdf" filename="report.pdf"/>
      <document name="sample-presentation.pdf">JVBERi0xLjQKJ....
        [clipped here]
        ....0CiUlRU9GCg==
      </document>
    </module>
  </modules>
  ```
  - Upload slides from external application to a live BigBlueButton session
  - 
- join meetings
  - Example Requests:
    - http://yourserver.com/bigbluebutton/api/join?meetingID=test01&password=mp&fullName=John&checksum=1234
    - http://yourserver.com/bigbluebutton/api/join?meetingID=test01&password=ap&fullName=Mark&checksum=wxyz
    - http://yourserver.com/bigbluebutton/api/join?meetingID=test01&password=ap&fullName=Chris&createTime=273648&checksum=abcd
  - Example Response:
  ```XML
  <response>
    <returncode>SUCCESS</returncode>
    <messageKey>successfullyJoined</messageKey>
    <message>You have joined successfully.</message>
    <meeting_id>640ab2bae07bedc4c163f679a746f7ab7fb5d1fa-1531155809613</meeting_id>
    <user_id>w_euxnssffnsbs</user_id>
    <auth_token>14mm5y3eurjw</auth_token>
    <session_token>ai1wqj8wb6s7rnk0</session_token>
    <url>https://yourserver.com/client/BigBlueButton.html?sessionToken=ai1wqj8wb6s7rnk0</url>
  </response>
  ```
- end meetings
  - Example Requests:
    - http://yourserver.com/bigbluebutton/api/end?meetingID=1234567890&password=mp&checksum=1234
  - Example Response:
  ```XML
  <response>
    <returncode>SUCCESS</returncode>
    <messageKey>sentEndMeetingRequest</messageKey>
    <message>
      A request to end the meeting was sent.  Please wait a few seconds, and then use the getMeetingInfo or isMeetingRunning API calls to verify that it was ended
    </message>
  </response>
  ```
- insert documents
  - Example Request:
    - https://yourserver.com/bigbluebutton/api/insertDocument?[parameters]&checksum=[checksum]
    - In body same as preupload slides
- get recordings for past meetings
  - Example Requests:
    - http://yourserver.com/bigbluebutton/api/getRecordings?checksum=1234
    - http://yourserver.com/bigbluebutton/api/getRecordings?meetingID=CS101&checksum=abcd
    - http://yourserver.com/bigbluebutton/api/getRecordings?meetingID=CS101,CS102&checksum=wxyz
    - http://yourserver.com/bigbluebutton/api/getRecordings?recordID=652c9eb4c07ad49283554c76301d68770326bd93-1462283509434&checksum=wxyz
    - http://yourserver.com/bigbluebutton/api/getRecordings?recordID=652c9eb4c07ad49283554c76301d68770326bd93-1462283509434,9e359d17635e163c4388281567601d7fecf29df8-1461882579628&checksum=wxyz
    - http://yourserver.com/bigbluebutton/api/getRecordings?recordID=652c9eb4c07ad49283554c76301d68770326bd93&checksum=wxyz
    - http://yourserver.com/bigbluebutton/api/getRecordings?recordID=652c9eb4c07ad49283554c76301d68770326bd93,9e359d17635e163c4388281567601d7fecf29df8&checksum=wxyz
    - http://yourserver.com/bigbluebutton/api/getRecordings?state=published&offset=20&limit=10&checksum=abc123
  - Example Response: See Documentation
- delete recordings
  - Example Requests:
    - http://yourserver.com/bigbluebutton/api/deleteRecordings?recordID=record123&checksum=1234
    - http://yourserver.com/bigbluebutton/api/deleteRecordings?recordID=record123,recordABC&checksum=wxyz
  - Example Response:
- updateRecordings
  - Example Requests:
    - http://yourserver.com/bigbluebutton/api/updateRecordings?recordID=record123&meta_Presenter=Jane%20Doe,meta_category=FINANCE,meta_TERM=Fall2016&checksum=1234
- upload closed caption files for meetings (uploadRecordingTextTracks)
  - Resource URL:
    - POST http://yourserver.com/bigbluebutton/api/putRecordingTextTrack
  - Response Type: JSON
- getRecordingTextTracks
  - Resource URL:
    - GET http://yourserver.com/bigbluebutton/api/getRecordingTextTracks?[parameters]&checksum=[checksum]
- getMeetingInfo
  - Example Requests:
    - http://yourserver.com/bigbluebutton/api/getMeetingInfo?meetingID=test01&checksum=1234
  - Example Response: XML See Dokumentation, will also list the breakout rooms of a meeting
- getMeetings
  - Example Requests:
    - http://yourserver.com/bigbluebutton/api/getMeetings?checksum=1234
  - Example Response: XML: Array of meeting

**Comment by Elweyn** [comment]
[PresentationVideoKonferenz.odp](https://github.com/dreammall-earth/dreammall.earth/files/13648205/PresentationVideoKonferenz.odp)
