### ISSUE TITLE
🐛 [Bug] Iframe too big on mobile

### ISSUE THREAD

**Issue by Bettelstab** [dreammall-earth/dreammall.earth#2125]
## 🐛 Bug

dazu gehört 
#2317 

On mobile (Android, Chrome 128.0.6613.127), the iframe with BBB meeting is too big / tall, so it overlaps with the bottom bar.
The table page is scrollable, which should not be the case.

<img width="362" alt="Screenshot 2024-09-13 at 11 30 00" src="https://github.com/user-attachments/assets/db5a7e83-cf73-40b5-bbc9-f8c6f3181c15">

**Comment by ogerly** [comment]
for such things we need BrowserStack, since we are open source, we get free access
