### ISSUE TITLE
🐛 [Bug] Gradient on border of rounded corners causes problems

### ISSUE THREAD

**Issue by ulfgebhardt** [dreammall-earth/dreammall.earth#2135]
## 🐛 Bug

Gradient on border of rounded corners causes problems.

@sebastian2357 described that gradients on borders of rounded corners cause problems and have downsides if implemented.

This Issue is made to clarify if there is a technical problem which affects the design capabilities.
Please clarify if we can use gradients on rounded borders or not and have @Hardy-Hart-am-Start adjust the design if needed.
If we can implement this kind of style, please implement it according to the designs.

This is also problematic with authentik.

**Comment by Bettelstab** [comment]
I found a solution which seems to be compatible with modern browsers: https://caniuse.com/?search=mask-composite

`<div class="box">
  foo
  lalelu
  <div class="inner">
    yeah
  </div>
</div>`

`.box {
  position: relative;
  height: 200px;
  padding: 20px;
  border-radius: 25px; 
}

.box::before {
  content: "";
  position: absolute;
  inset: 0;
  border-radius: 25px; /*1*/

  border: 10px solid transparent; /*2*/
  background: linear-gradient(45deg,red,blue) border-box; /*3*/
  -webkit-mask: /*4*/
     linear-gradient(#fff 0 0) padding-box, 
     linear-gradient(#fff 0 0);
  -webkit-mask-composite: xor; /*5'*/
          mask-composite: exclude; /*5*/
}


.inner {
  background: green;
  margin: 10px;
}`

**Comment by Bettelstab** [comment]
PS: We have to use fallbacks though.

E.g.:
Wrap the whole pseudo element in 
```
@supports (-webkit-mask-composite: xor) { // also mask-composite:exclude
```
and give alternative.

**Comment by Bettelstab** [comment]
I checked again and actually, browser support is excellent. Just some older browsers need the -webkit prefix.
https://caniuse.com/?search=mask-composite
