### ISSUE TITLE
🐛 [Bug] Payment: Missing data & correct data

### ISSUE THREAD

**Issue by ulfgebhardt** [dreammall-earth/dreammall.earth#2140]
## 🐛 Bug

The Payment page requires to have correct data.

Clarify the correct IBAN & BIC

Furthermore Heimo reported that his Bank requires the full Bank Name.

- Display real data for IBAN, BIC & Bank Name
- Include Bank Name as field
- Rename Referenz to `Verwendungszweck`

Requirements from Heimo:
![image](https://github.com/user-attachments/assets/7555f038-9a75-47c9-bd4e-0f98e1c018c8)

Requirements from Sushidave
For e-banking payments from CH to a bank abroad, at least this data is required:
- IBAN
- Name and address of the beneficiary

**Comment by ulfgebhardt** [comment]
@Elweyn has the data
@heimo has the info what additional data is required

**Comment by sushidave** [comment]
@ulfgebhardt 
For e-banking payments from CH to a bank abroad, at least this data is required:
* IBAN
* Name and address of the beneficiary
@Tirokk @Elweyn
