### ISSUE TITLE
🐛 [Bug] Share Table has no functionality

### ISSUE THREAD

**Issue by ulfgebhardt** [dreammall-earth/dreammall.earth#2144]
## 🐛 Bug

Share Table has no functionality
![image](https://github.com/user-attachments/assets/cf06008b-5b82-430e-93c9-2a52f56fc8bf)

**Comment by Bettelstab** [comment]
Which link do we want to share here?
If we want to share the guest link (with #1948), we can do that only with tables with active meetings. But in this list are also tables without an active meeting.
If we share the internal dreammall link like `/table/23`, does that make sense? What would be the use case?

**Comment by ulfgebhardt** [comment]
Gebe ich so an @Hardy-Hart-am-Start weiter

**Comment by ulfgebhardt** [comment]
Closing in favor of solution decided for: https://github.com/dreammall-earth/dreammall.earth/issues/2222
