### ISSUE TITLE
🐛 [Bug] Invite to table has no functionality

### ISSUE THREAD

**Issue by ulfgebhardt** [dreammall-earth/dreammall.earth#2145]
## 🐛 Bug

Invite to table has no functionality

When editing a table I do get a Dialog for inviting new members. Changing anything here has no effect.
![image](https://github.com/user-attachments/assets/6ba7d799-2850-4c6a-9b07-8691e7bc03d1)

**Comment by Elweyn** [comment]
@ulfgebhardt this will be resolved if #1026 is finished
