### ISSUE TITLE
🚀 [Feature] Implement Hover on Starmap

### ISSUE THREAD

**Issue by ulfgebhardt** [dreammall-earth/dreammall.earth#2147]
## 🚀 Feature

Implement Hover on Starmap
![image](https://github.com/user-attachments/assets/1736f5d6-0173-41d2-b990-a0fce4b1a5aa)

**Comment by ulfgebhardt** [comment]
Make star hover/click field bigger then the star

**Comment by sebastian2357** [comment]
A few thoughts which should be taken into account:

- panel behavior at the edge of the screen
- when the panel is open and the map will be moved then the panel should be moved as well or be closed
