### ISSUE TITLE
🐛 [Bug] iOS: Mobile drawer partly visible in closed state

### ISSUE THREAD

**Issue by Bettelstab** [dreammall-earth/dreammall.earth#2235]
## 🐛 Bug
<img width="321" alt="Screenshot 2024-09-18 at 20 46 46" src="https://github.com/user-attachments/assets/3fa9ff2d-7a5a-4d63-80e5-194f8bfe3bb8">

**Comment by ulfgebhardt** [comment]
This happens when navigating to cockpit and is persistent on the starmap after

**Comment by sebastian2357** [comment]
@Elweyn @Tirokk 
I can not reproduce this issue. I tried it on desktop and mobile android. Could someone validate, if the issue is still present on iOS, because the screenshot shows an old version. Maybe the issue is already solved.

**Comment by Tirokk** [comment]
I can reproduce this error @sebastian2357 @Elweyn in my local iPhone simulator.
