### ISSUE TITLE
🐛 [Bug] Mobile: In BBB Meeting importent BBB buttons are behind header and not interactable, when DreamMall page is scrolled down

### ISSUE THREAD

**Issue by mahula** [dreammall-earth/dreammall.earth#2251]
## Problem
On mobile devices important BBB buttons (e.g. save button in BBB settings) might be not interactable, when DreamMall page has been scrolled down.

![mobile-bbb-buttons_covered_by_dreammall_header](https://github.com/user-attachments/assets/8e0dcb1a-0f8c-4314-97b0-09311c3000df)

### How to reproduce
On a mobile device
1. Log into the DreamMall (our stage)
2. Create or join a table
3. Open the BBB settings via the 3 dots in the iframe's upper right corner
4. Scroll down the DreamMall page outside the iframe
5. See the BBB settings' save button at same level as the _Weltencafé/Cockpit_ element in header
6. Tap the BBB settings' save button to save the settings
7. No effect
8. Scroll up the DreamMall page outside the iframe (the BBB settings' save button is not covered by the header)
9. Tap the BBB settings' save button to save the settings
10. It works as expected

**Comment by ulfgebhardt** [comment]
- Iframe unterhalb des Menüs
- Iframe rounded corners (desktop 4 round & mobil 2 round top)
- left-right no border

**Comment by ulfgebhardt** [comment]
Closing in favor of https://github.com/dreammall-earth/dreammall.earth/issues/2317
