### ISSUE TITLE
💬 [Question] Mobile: user friendly entrance to DreamMall BBB meeting

### ISSUE THREAD

**Issue by mahula** [dreammall-earth/dreammall.earth#2260]
## 💬 Question
It has been reported, entering a table (BBB meeting with current layout config) on a mobile device seems confusing:

You do not see the participants'videos,neither the participants list, but the open _public chat_
![mobile_probleme_01](https://github.com/user-attachments/assets/7eba8a4c-b5c7-4251-aeea-bd1ac8de398d)

You need to close the _public chat_ to see the participants list
![mobile_probleme_02](https://github.com/user-attachments/assets/ad643ce7-c3dc-4ccc-b65e-f5607802f9b3)

and close the participants list to see the participants' videos and presentation
![mobile_probleme_03](https://github.com/user-attachments/assets/0ef7010d-4eb0-4b72-bb1b-26aac5c3b3d0)

## Possible Solution

a. Decide for a different default BBB layout, e.g.SmartLayout, to fit both - the core ideahow users are introduced to a BBB meetig and how they are presented on mobile devices
b. If possible via the BBB API @Mogge , set a specific layout for mobile users
c. Document and introduce the DreamMall users how toperceive and use the BBB meetings

**Comment by ulfgebhardt** [comment]
Preferred solution: a
