### ISSUE TITLE
🐛 [Bug] Dynamic Height of DM Panel

### ISSUE THREAD

**Issue by sebastian2357** [dreammall-earth/dreammall.earth#2406]
## 🐛 Bug

The current approach provides only a static height for the DM Panel, but for the XP it would be nicer if the panel has only the needed size to present its content.

**Comment by ulfgebhardt** [comment]
Dynamische Höhe

**Comment by ulfgebhardt** [comment]
Closing in favor of https://github.com/dreammall-earth/dreammall.earth/issues/2531
