### ISSUE TITLE
💬 [Question] Desired behaviour for invite button while in meeting

### ISSUE THREAD

**Issue by Bettelstab** [dreammall-earth/dreammall.earth#2409]
It was requested to add an "Invite" button in the new sidebar, to open a new mall talk. The main way to open new mall talks should be via the DreamMall button, so the idea was to show that to the users by simply opening that button.

But, when I'm in a meeting (= currently, on the table page), the DreamMall button shows options for the current meeting.

What is the desired behaviour when clicking "Invite" in a meeting?

- Ask the user to leave the meeting first?
- Render the create malltalk dialog in the button?
- Something else?

**Comment by ulfgebhardt** [comment]
- Claudia is not comfortable with the design of the button

Different states:
- in my malltalk
- in a malltalk
- in a project table
- no meeting

**Comment by ulfgebhardt** [comment]
From #2478 

Invite Button in Sidemenü.

has two states:
- Invite to own Malltalk (Einladen)
- Create own Malltalk (Tisch eröffnen) -> Shows the user a Hint that he will leave the current Meeting

Clarify exactly what is to be implemented and how it works

**Comment by ulfgebhardt** [comment]
Mein MallTalk -> Leute Einladen
Anderer Malltalk -> Eigener Tisch öffnen -> Popup Feld Warning -> Button eigener Tisch
Projekt Tisch -> Moderator -> Einladen
Projekt Tisch -> Kein Moderator -> Ausgegraut

**Comment by ulfgebhardt** [comment]
closing in favor of https://github.com/dreammall-earth/dreammall.earth/issues/2666
