### ISSUE TITLE
🚀 [Feature] iOS: BBB only supports Safari browser

### ISSUE THREAD

**Issue by mahula** [dreammall-earth/dreammall.earth#2426]
## 🚀 Feature
For mobile iOS devices BBB doesnot support other browsers than the native Safari.
If using another browser toenter a BBB meeting results in this hint and not being ableto actually use the BBB meeting.
We should inform the DreamMall users to use Safari on, if on a iOS device (=>Marketing) 
![iOS_no_support_other_browsers](https://github.com/user-attachments/assets/089e9b18-d1ef-4397-b89f-a15f6c34b66e)

**Comment by ulfgebhardt** [comment]
I think this can be closed, since it is not relevant for development. We cannot change this behaviour. It only applies to the fruit computers mobile OS.
