### ISSUE TITLE
🚀 [Feature] Design suggestions from user tests

### ISSUE THREAD

**Issue by mahula** [dreammall-earth/dreammall.earth#2435]
Suggestions, questions and hints for design and fuctionality collected from user tests:

#### About Me section categories
If the categories have already been changed/filled by the user, the meaning of the icons' meening placeholders arenot visible anymore.
Hints at hover would help to understand the icons' meanings

![cockpit_about_me_categories_hint](https://github.com/user-attachments/assets/612192c1-0437-4400-abc5-ff3b523d1dd2)

#### Upgrade Section
At the moment the wording is incoherent - _Premuim_ vs _Pro_

![cockpit_pro_naming](https://github.com/user-attachments/assets/10f212c7-5f1f-431b-963e-df74a21ec075)

#### The clarity towads the user seems unclear:
- DreamMall calls it _Tables_ and also _Mall Talks_
- in BBB the meetings are named "_Konferenz_" towards the user, e.g. when entering/leaving a BBB meeting
  ![konferenz](https://github.com/user-attachments/assets/0d0be661-2560-43a1-9100-61ce359f6baf)

- since it is about videomeetingsand presentation, test user suggests awording in this direction
This shows, that we should care about communication the DreamMall vision and concept behind the Weltencafé and its tables clearly to the users from the beginning.
#### Betterwording for tablecration finish
Instead of _Fertig_ something encouraging ar activating like _Los geht's_ has been suggested
![tisch_erstellen_fertig](https://github.com/user-attachments/assets/c48a0b59-8bd0-4baf-8da3-9dcb137a3f4e)

Here the suggestion is to name this "Tisch beitreten" / "Tisch eröffnen"

#### Audio Settings in Browser
The user decided to join a BBB meeting just listening without microphone (BBB asks you when entering)
![konferenz](https://github.com/user-attachments/assets/0d0be661-2560-43a1-9100-61ce359f6baf)

In the meeting the user wants to active their microphone via the BBB UI, but coudnot get the microphone activated.
This action might also requirereactivating the microphone access in the browser (next to the URL field).
How to achieve the this shouldbe communicated to the users in the beginning (=>marketing/PR).
![bbb_audio](https://github.com/user-attachments/assets/4ae0032c-2d66-4bd6-85ec-cbd6e07f1c38)

#### Download Presentation (Image Size)
The user downloaded his presentation, but it had adifferent image size than expected (Heimo could elaborate more on this)

**Comment by Hardy-Hart-am-Start** [comment]
**1. Download Presentation (Image Size)**

Diese Funktion wird erst in den nächsten Versionen spezifiziert und wir mit weiteren Funktionen wie eine Auswahl des Dateiformats versehen. bis dahin kann geprüft werden in wie weit die Oberfläche des Zeichnens dazu in der Lage ist Vektorbasierend zu agieren, da dies die Image Size beeinträchtigt.

**2. Audio Settings in Browser**

Wenn eine Steuerung über die Domainleiste möglich ist wäre das Ideal. Prinzipiell wird der BBB erst in der nächsten Version genauer spezifiziert.

**3. Betterwording for tablecration finish**
Bitte "Tisch erstellen" zu "Tisch eröffnen" ändern. Auch diese Version für das Wording ist nicht dauerhaft jedoch ein Kompromiss um zunächst aus dem UX verhalten des Users zu lernen.

**4. Table related wording**

Wenn möglich folgendes benutzen. 
Für Malltalk- und Projekttische:"Wie möchtest du teilnehmen: Zuhören oder Mitreden?"

**5. About Me section categories**

Hierzu wurde eine Lösung auf Figma angeboten die noch aussteht. 

<img width="929" alt="Bildschirmfoto 2024-10-01 um 13 49 12" src="https://github.com/user-attachments/assets/2670a12e-fd92-41ad-9f59-cabcf93c28e5">

<img width="389" alt="Bildschirmfoto 2024-10-01 um 13 49 19" src="https://github.com/user-attachments/assets/fe754c7e-5483-404f-8610-3859e64d03fe">

Bitte beachten das der Dropdown Button noch fehlt

**6. Upgrade Section**

Dieses Fehlt ist in der Abstimmung und abhängig vom Prizing Plan, gilt nur als Entwurf für ein Generiertes Feld, was dem User die Möglichkeit bieten soll das Abo zu jederzeit Wahrzunehmen.

**Comment by ulfgebhardt** [comment]
Closing in favor of
- https://github.com/dreammall-earth/dreammall.earth/issues/2530
- https://github.com/dreammall-earth/dreammall.earth/issues/2529
