### ISSUE TITLE
🔧 [Refactor] BBB: Change or remove English defaultWelcomeMessageFooter

### ISSUE THREAD

**Issue by mahula** [dreammall-earth/dreammall.earth#2554]
Motivation
------
In a BBB meeting the `defaultWelcomeMessageFooter` text has been reported to be rahter irritatig than helpful for the users.
![Bildschirmfoto vom 2024-10-02 13-14-11_01](https://github.com/user-attachments/assets/dbaaa418-0932-44c1-9ce0-a0124b987711)

Possible Solution
------
Set it to an empty string or replace it by a more DreamMall related mesage to welcome users in a meeting or provide helpful information.
This can be set server-side in the configuration file [bigbluebutton.properties](https://github.com/bigbluebutton/bigbluebutton/blob/62d03ee04bcd0e0fdbdc44b98fb50e2c9d04bb29/bigbluebutton-web/grails-app/conf/bigbluebutton.properties#L185).

**Comment by ulfgebhardt** [comment]
Fixed as following:
![Image](https://github.com/user-attachments/assets/fc815c3a-9e91-4b14-a916-2e9b2800d49c)

**Comment by ulfgebhardt** [comment]
closing as ok as it currently is
