### ISSUE TITLE
🔧 [Refactor] BBB replace default presentation

### ISSUE THREAD

**Issue by mahula** [dreammall-earth/dreammall.earth#2568]
Motivation
------
BBB's default presentation has been reported as  rather irritating then helpful.
The icons have been mistaken for interactive elements (e.g the chat icon to start a chat).
It does not really support the user to find their way around the BBB interface.

![bbb_default_praesi](https://github.com/user-attachments/assets/0daef35c-07a8-4dc5-a4d0-b7f717bf72c7)

Possible Solution
------
Provide a DreamMall branded graphical overview of the main BBB functions and controls similar to [Senfcall.de](https://www.senfcall.de/).

A custom presentation can be set
- programmatically via the `create` call's `preUploadedPresentation` parameter (see the see the [BBB API doc](https://docs.bigbluebutton.org/development/api/#get-post-create))
- [server-side config](https://github.com/bigbluebutton/bigbluebutton/blob/2d3bb50709a5db521b4e6ddec470ecd05610a1da/docs/docs/administration/customize.md#change-the-default-presentation)

![bbb_senfcall_praesi](https://github.com/user-attachments/assets/061d8ee6-c879-40c3-854e-8923084173f6)

**Comment by ulfgebhardt** [comment]
Closing in favor of #2172
