### ISSUE TITLE
🐛 [Bug] Frontend: Cockpit Table Creation Radio Button wrong Text

### ISSUE THREAD

**Issue by mahula** [dreammall-earth/dreammall.earth#2571]
## 🐛 Frontend: Cockpit Table Creation Radio Button wrong Text

When creating a table in the cockpit, the radio button does not display the text "public", but "private" in both states:

![tisch_erstellen_radio_button](https://github.com/user-attachments/assets/766ad1b2-9570-4b48-8f84-37ad49ffcfe1)

**Comment by ulfgebhardt** [comment]
fixed
