### ISSUE TITLE
🐛 [Bug] Frontend: Wrong Wording when inviting Peoplei n Table Creation

### ISSUE THREAD

**Issue by mahula** [dreammall-earth/dreammall.earth#2586]
## 🐛 Frontend: Wrong Wording when inviting Peoplei n Table Creation
Ithas been reported, that the term _Mitmoderatoren_ is wrong (see [locale JSON files](https://github.com/search?q=repo%3Adreammall-earth%2Fdreammall.earth+chooseModerators+language%3AJSON&type=code&l=JSON)):

![Mitmoderatoren](https://github.com/user-attachments/assets/f98142ef-c918-49a0-a63c-db70e3bbdca8)

**Comment by ogerly** [comment]
Choose your moderator team.

Wähle dein Moderator-Team.
