### ISSUE TITLE
🐛 [Bug] backend Tests Flaky

### ISSUE THREAD

**Issue by ulfgebhardt** [dreammall-earth/dreammall.earth#330]
## 🐛 Bug

Backend test can fail for unknown reason: https://github.com/dreammall-earth/dreammall.earth/actions/runs/8241168363/job/22537888687?pr=329

![image](https://github.com/dreammall-earth/dreammall.earth/assets/1238238/0e9315e3-6a35-4e79-b105-941a8586669d)

![image](https://github.com/dreammall-earth/dreammall.earth/assets/1238238/3418b7cb-b6c8-4863-a59d-1cf95e18ba8d)

- Decoupling Issue?
- Wait for all timers?

**Comment by Mogge** [comment]
Is this still an issue? Did someone observe this in the last weeks?
