### ISSUE TITLE
🚀 [Feature] Tisch: Betreten eines zugänglichen Tisches

### ISSUE THREAD

**Issue by mahula** [dreammall-earth/dreammall.earth#349]
## 🚀 Feature
Als Nutzer
Will  ich mir zugängliche Tische/Räume angezeigt haben und betreten können

### Szenarien
- [ ] Erfolgreiches Betreten zugänglichen Tisches/Raumes
       Gegeben
     &nbsp;&nbsp;&nbsp;&nbsp;  Ich bin registriert und eingeloggt
     &nbsp;&nbsp;&nbsp;&nbsp; Es gibt einen für mich zugänglichen Tisch/Raum
       Wenn ich auf der Weltencafé-Seite bin
       Dann wird der Tisch/Raum angezeigt
       Wenn ich den Tisch/Raum anklicke
       Dann komme ich in die in die BBB-Session des Raumes/Tisches

**Comment by Elweyn** [comment]
This szenario is deployed on stage1 from master branch.
Is it finished or do we need something more to see this as done?
