### ISSUE TITLE
💬 [Question] Authentik Design Options

### ISSUE THREAD

**Issue by ulfgebhardt** [dreammall-earth/dreammall.earth#375]
## 💬 Question

Present Hardi the design options for Authentik with all data so he can provide the correct formats, Images and other Ressources.

**Comment by ulfgebhardt** [comment]
This describes what options we have to customize the design in Authentik.

### Processes
We currently have the following processes which is each individually designable:
- Authentication (login)
- Authorization
- Enrollment (register)
- Invalidation (logout)

### Layout
In Authentik we can display processes in 5 different layout modes:
- Stacked:
![image](https://github.com/dreammall-earth/dreammall.earth/assets/1238238/853f5feb-e0de-4389-8f57-854f5aa8435c)
- Content left:
![image](https://github.com/dreammall-earth/dreammall.earth/assets/1238238/908d292a-3434-4bed-90a8-f8de7bd31bd3)
- Content right:
![image](https://github.com/dreammall-earth/dreammall.earth/assets/1238238/e5eb9581-20f3-4038-a3b5-4c399b2b26d1)
- Sidebar left:
![image](https://github.com/dreammall-earth/dreammall.earth/assets/1238238/49092799-b8e6-4201-9b75-591f74c7a7b5)
- Sidebar right:
![image](https://github.com/dreammall-earth/dreammall.earth/assets/1238238/7339ae3f-c194-417a-9a04-c0ac4afee08e)

### Darmkode

There is also a darkmode

![image](https://github.com/dreammall-earth/dreammall.earth/assets/1238238/55258c00-1a14-4402-b6ee-cc0ef98f8419)
![image](https://github.com/dreammall-earth/dreammall.earth/assets/1238238/b3ba7427-376c-46e1-aebf-4e8487d4f000)
![image](https://github.com/dreammall-earth/dreammall.earth/assets/1238238/67d46810-704d-4387-a96d-ceaed4c98b76)
![image](https://github.com/dreammall-earth/dreammall.earth/assets/1238238/5002cc96-e455-4e37-984a-a98b2b8fc29c)


### Options
We can define the following things out of the box:
- Background
- Logo (global)
- Favicon (global)
- Almost all texts

Furthermore we can mount a `custom.css` file to adjust the style like colors, margins, ...

### Library

Authentik also has an userinterface, which we wont use as of current planning.

He we see the global logo and the AppIcon we can define for each App.

![image](https://github.com/dreammall-earth/dreammall.earth/assets/1238238/d6f54283-9fc3-4d7b-92a1-121977370987)

### Ressources
- https://docs.goauthentik.io/docs/interfaces/user/customization#custom-css
- https://github.com/goauthentik/authentik/issues/2364
- https://www.youtube.com/watch?v=YawgyM509ng
- https://www.reddit.com/r/selfhosted/comments/18ymm49/how_do_i_enable_dark_mode_in_authentik/

**Comment by Hardy-Hart-am-Start** [comment]
[Login.pdf](https://github.com/dreammall-earth/dreammall.earth/files/14899049/Login.pdf)
[Register.pdf](https://github.com/dreammall-earth/dreammall.earth/files/14899050/Register.pdf)

Mein Vorschlag für die FELDER
