### ISSUE TITLE
🚀 [Feature] Contact Form send from backend to Brevo

### ISSUE THREAD

**Issue by ulfgebhardt** [dreammall-earth/dreammall.earth#51]
## 🚀 Feature

Contact Form send from backend to Brevo

![image](https://github.com/dreammall-earth/dreammall.earth/assets/1238238/ee5d8b64-9675-45e9-bdd3-5c09af6a7630)

Data:
- Vorname
- nachname
- email
- frage (content)
- (dsvgo)

Goal:
- Send Static Data in the given Form from our backend to brevo.
- Receive two emails:
  - One for the admin/support:
    - Daten aus Kontaktformular an uns (template1)
  - one for the Questioneer:
    - obige ummantelt mit Info, dass diese Daten an die DramMall E-Mail versendet wurden,
an Nutzer-E-Mail-Adresse (template2)

**Comment by Elweyn** [comment]
@ulfgebhardt soll hier ein Contact in Brevo erstellt werden oder soll dies nur in dem Newsletter call geschehen?
