### ISSUE TITLE
🐛 [Bug][Authentik] On Sign-In Email Input Field Text Stays White while Editing

### ISSUE THREAD

**Issue by Tirokk** [dreammall-earth/dreammall.earth#624]
## 🐛 Bug

macOS Safari and Firefox ( @Tirokk )

- On Sign-In Email Input Field Text Stays White while Editing: see screen shot
  - text is marked to show that it is there

<img width="1526" alt="Bildschirmfoto 2024-04-26 um 10 01 18" src="https://github.com/dreammall-earth/dreammall.earth/assets/25344101/f42fa85e-28d4-4af9-b779-502908397a47">

**Comment by Elweyn** [comment]
@ulfgebhardt 
This has been changed by @mahula and @roschaefer to what it was before the gradiant so it should not be a problem anymore
