### ISSUE TITLE
💥 [DevOps] Authentik/BBB/Frontend: IFrame auf stage1 und live erlauben

### ISSUE THREAD

**Issue by Elweyn** [dreammall-earth/dreammall.earth#946]
## 💥 DevOps
As user I want to stay on the same platform to Sign In, Sign Up and joinMeetings.
We now can't use the IFrame to auth.dreammall.earth to refresh the token.

## 🤖 ToDos
- [ ] Nginx accepts X-Frame from auth.dreammall.earth
- [x] Nginx accepts X-Frame from cafe.dreammall.earth

**Comment by Bettelstab** [comment]
Maybe this information helps:
Authentik seems to prohibit it's usage in iframes by setting CSP frame-ancestors to 'self'. X-Frame-Options are ignored when a CSP with this setting is present, so we need to override the CSP instead.
